import { ArrowRight, Check, ChevronRight, Clipboard, Code2, Download, ExternalLink, FileCode2, KeyRound, Layers3, LockKeyhole, Network, Play, ShieldCheck, Terminal, WalletCards, Webhook, X } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { developerSdkSnippet } from "@/lib/developer";

const logo = "/DRUTO_D_logo.png";
const sdkPackageUrl = "/manus-storage/druto-sdk-0.1.0_4dbf00a5.zip";
const sdkGuideUrl = "/manus-storage/GUIDE_60d3c182.md";
const sdkReadmeUrl = "/manus-storage/README_6ca76bed.md";

const curlSnippet = `curl -X POST https://api.druto.example/v1/payment-intents \\
  -H "Authorization: Bearer druto_test_..." \\
  -H "Content-Type: application/json" \\
  -H "Idempotency-Key: order_123_seller_456" \\
  -d '{
    "externalOrderId": "order_123_seller_456",
    "amount": "24.00",
    "asset": "USDC",
    "network": "arc-testnet",
    "itemName": "Arc Starter × 1",
    "seller": {
      "marketplaceId": "marketplace_abc",
      "sellerId": "seller_456"
    },
    "returnUrl": "https://shop.example/orders/123/paid"
  }'`;

const webhookSnippet = `import { verifyDrutoWebhook } from "@druto/sdk";

const event = verifyDrutoWebhook({
  rawBody,
  signature: request.headers.get("druto-signature"),
  secret: process.env.DRUTO_WEBHOOK_SECRET,
  toleranceSeconds: 300
});

if (event.type === "payment.verified" && !await alreadyProcessed(event.id)) {
  await markSellerOrderPaid(event.data.externalOrderId);
  await recordProcessedEvent(event.id);
}`;

function CodeBlock({ code, language = "typescript" }: { code: string; language?: string }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => { try { await navigator.clipboard.writeText(code); setCopied(true); window.setTimeout(() => setCopied(false), 1400); } catch { setCopied(false); } };
  return <div className="dev-code-block"><div className="dev-code-head"><span><span className="dev-code-dot" /> {language}</span><button onClick={copy}><Clipboard size={13} /> {copied ? "Copied" : "Copy"}</button></div><pre><code>{code}</code></pre></div>;
}

function DocLink({ href, children }: { href: string; children: React.ReactNode }) { return <a href={href} className="developer-doc-link">{children}<ChevronRight size={14} /></a>; }

export default function DeveloperHub() {
  return <div className="developer-site">
    <header className="developer-nav"><Link href="/" className="public-brand"><img src={logo} alt="" /><strong>druto</strong></Link><div className="developer-nav-center"><span className="developer-nav-active">Developer Hub</span><Link href="/developers/start">Start with Druto</Link><a href="#quickstart">Quickstart</a><a href="#live-demo">Live demo</a><a href="#reference">API reference</a><a href="#errors">Errors</a><a href="#webhooks">Webhooks</a></div><div className="developer-nav-actions"><span className="developer-version">Arc Testnet</span><Link href="/dashboard" className="button button-primary">Open dashboard <ArrowRight size={14} /></Link></div></header>
    <main>
      <section className="developer-hero"><div><span className="public-kicker"><Code2 size={14} /> Druto integration platform</span><h1>Build the payment flow your marketplace <em>actually owns.</em></h1><p>Everything needed to accept USDC on Arc Testnet: seller onboarding, server-created Payment Intents, hosted wallet checkout, verified webhooks, and a dashboard that stays in sync.</p><div className="developer-hero-actions"><Link href="/developers/start" className="button button-primary public-large-button">Start with Druto <ArrowRight size={16} /></Link><a href="#sdk-kit" className="button button-quiet public-large-button"><Download size={16} /> Get the SDK kit</a></div></div><aside className="developer-hero-panel"><div className="dev-panel-top"><span><span className="live-dot" /> Integration contract</span><span className="mono-id">v0.1</span></div><div className="dev-panel-line"><span>Network</span><strong>Arc Testnet</strong></div><div className="dev-panel-line"><span>Asset</span><strong>USDC · 6 decimals</strong></div><div className="dev-panel-line"><span>Buyer methods</span><strong>Wallet + QR</strong></div><div className="dev-panel-line"><span>Seller routing</span><strong>Server-resolved</strong></div><div className="dev-panel-foot"><ShieldCheck size={14} /> Verification before fulfillment</div></aside></section>
      <section className="developer-stat-row"><div><strong>01</strong><span>Marketplace credential</span></div><div><strong>06</strong><span>Integration steps</span></div><div><strong>0</strong><span>Private keys requested</span></div><div><strong>1</strong><span>Canonical event source</span></div></section>
      <section className="developer-section developer-demo-section" id="live-demo"><div className="developer-section-heading"><div><span className="eyebrow">Live presentation runbook</span><h2>Show the complete Arc payment loop.</h2><p>Use this sequence to demonstrate a real marketplace purchase on Arc Testnet with the configured Druto merchant account. Keep the buyer wallet ready before you begin.</p></div><span className="developer-section-index">DEMO / ARC</span></div><div className="developer-demo-grid"><div className="developer-demo-list"><div><span>01</span><div><strong>Open the marketplace</strong><small>Browse the demo catalog, add two or three items to the cart, and show the seller labels and total.</small></div></div><div><span>02</span><div><strong>Checkout normally</strong><small>Enter the buyer details and choose <em>Pay with Druto</em> as the payment method.</small></div></div><div><span>03</span><div><strong>Review Druto checkout</strong><small>Confirm Arc Testnet, USDC, the exact amount, the server-resolved receiving wallet, and the order reference.</small></div></div><div><span>04</span><div><strong>Pay with wallet or QR</strong><small>Connect an EVM wallet or scan the QR code. Approve only the displayed USDC transfer in the wallet prompt.</small></div></div></div><div className="developer-demo-proof"><div className="dev-panel-top"><span><span className="live-dot" /> Real testnet proof</span><span className="mono-id">USDC / ARC</span></div><div className="developer-demo-proof-row"><span>Network</span><strong>Arc Testnet</strong></div><div className="developer-demo-proof-row"><span>Transfer</span><strong>Wait for succeeded</strong></div><div className="developer-demo-proof-row"><span>Proof</span><strong>Open Arcscan</strong></div><div className="developer-demo-proof-row"><span>Operations</span><strong>Open Druto dashboard</strong></div><div className="developer-demo-note"><ShieldCheck size={15} /><span>Only a verified receipt is treated as paid. A submitted transaction hash is not enough.</span></div></div></div><div className="developer-demo-after"><div><span>05</span><strong>Show Arcscan</strong><small>Open the transaction hash from the buyer receipt and verify the Arc Testnet transaction, USDC token, amount, sender, and configured recipient.</small></div><div><span>06</span><strong>Show the seller dashboard</strong><small>Refresh Payments or Overview and show the verified payment, buyer/order context, receipt details, transaction hash, and seller balance/activity.</small></div><div><span>07</span><strong>Close the story</strong><small>Explain that Druto verifies onchain finality, emits a signed payment.verified event, and lets the marketplace fulfill safely.</small></div></div></section>
      <section className="developer-section" id="quickstart"><div className="developer-section-heading"><div><span className="eyebrow">Quickstart</span><h2>From seller onboarding to fulfillment.</h2></div><span className="developer-section-index">01 / 06</span></div><div className="developer-steps"><article><span>01</span><div><h3>Register the marketplace and seller</h3><p>Create a merchant account with your marketplace seller ID and intended Arc receiving wallet. Druto keeps the seller pending until ownership is proven.</p><DocLink href="#seller-ownership">Seller onboarding <ArrowRight size={13} /></DocLink></div></article><article><span>02</span><div><h3>Sign the ownership challenge</h3><p>Connect the seller wallet and sign a domain-bound message. This is an offchain signature; no transaction or gas is requested.</p><DocLink href="#seller-ownership">Ownership proof <ArrowRight size={13} /></DocLink></div></article><article><span>03</span><div><h3>Create an intent from your backend</h3><p>Send the order, amount, buyer context, and seller identity from a trusted server. Never accept a destination wallet from the browser.</p><DocLink href="#payment-intents">Payment Intent contract <ArrowRight size={13} /></DocLink></div></article><article><span>04</span><div><h3>Open the hosted checkout</h3><p>Redirect the buyer to the returned checkout URL. The buyer reviews the exact USDC amount and chooses an injected wallet or QR flow.</p><DocLink href="#checkout">Checkout behavior <ArrowRight size={13} /></DocLink></div></article><article><span>05</span><div><h3>Verify the Arc transfer</h3><p>Druto verifies recipient, token contract, chain ID, amount, and receipt finality before an intent becomes succeeded.</p><DocLink href="#verification">Verification boundary <ArrowRight size={13} /></DocLink></div></article><article><span>06</span><div><h3>Fulfill from the signed event</h3><p>Consume `payment.verified`, check its HMAC and event ID, then mark the seller order fulfilled exactly once.</p><DocLink href="#webhooks">Webhook contract <ArrowRight size={13} /></DocLink></div></article></div></section>
      <section className="developer-section developer-code-section" id="payment-intents"><div className="developer-section-heading"><div><span className="eyebrow">01 · Create payments</span><h2>Use the SDK, REST contract, or your own adapter.</h2><p>All paths create the same server-owned Payment Intent. The browser never chooses the merchant wallet.</p></div><span className="developer-section-index">API / SDK</span></div><div className="developer-code-grid"><div><div className="dev-tab-row"><span className="dev-tab-active">JavaScript SDK</span><span>REST</span></div><CodeBlock code={developerSdkSnippet} /></div><div><div className="dev-tab-row"><span className="dev-tab-active">HTTP</span><span>Request contract</span></div><CodeBlock code={curlSnippet} language="bash" /></div></div><div className="developer-contract-grid"><div><span className="eyebrow">Required fields</span><ul>{["externalOrderId — your order or seller-order reference", "idempotencyKey — stable key for safe retries", "amount — positive USDC decimal, up to 6 places", "seller.marketplaceId + seller.sellerId", "returnUrl — HTTPS buyer return destination"].map(item => <li key={item}><Check size={14} />{item}</li>)}</ul></div><div><span className="eyebrow">Returned session</span><p><code>id</code>, <code>checkoutUrl</code>, <code>displayAmount</code>, <code>asset</code>, <code>network</code>, <code>merchantAddress</code>, expiry, seller identity, and persisted order context.</p><span className="contract-note"><LockKeyhole size={13} /> Server resolves the approved wallet.</span></div></div></section>
      <section className="developer-section developer-split-section"><div className="developer-section-heading"><div><span className="eyebrow">02 · Multi-seller orders</span><h2>One cart. One intent per seller.</h2><p>Group the cart by seller before calling Druto. Each seller gets an independent amount, idempotency key, order context, receipt, and dashboard record.</p></div><span className="developer-section-index">SELLER ROUTING</span></div><div className="seller-flow"><div className="seller-flow-cart"><Layers3 size={21} /><strong>Marketplace cart</strong><small>3 items · 2 sellers</small></div><div className="seller-flow-branch"><i /><i /></div><div className="seller-flow-intents"><div><span className="live-dot" /><strong>Intent A</strong><small>Seller A · 12.00 USDC</small></div><div><span className="live-dot" /><strong>Intent B</strong><small>Seller B · 8.50 USDC</small></div></div><div className="seller-flow-result"><Webhook size={18} /><strong>payment.verified</strong><small>Fulfill each seller order once</small></div></div></section>
      <section className="developer-section" id="seller-ownership"><div className="developer-section-heading"><div><span className="eyebrow">03 · Seller setup</span><h2>Provision the seller integration.</h2><p>Register the seller identity, configure the payment destination, generate server credentials, and register the signed webhook endpoint.</p></div><span className="developer-section-index">SERVER SETUP</span></div><div className="ownership-grid"><div className="ownership-card"><div className="ownership-number">A</div><div><h3>Seller registration</h3><p>Send <code>marketplaceId</code>, <code>sellerId</code>, display name, and payment destination. The account record is durable.</p></div></div><div className="ownership-card"><div className="ownership-number">B</div><div><h3>Server credentials</h3><p>Create an API key and keep it on your backend. Register one HTTPS webhook for payment synchronization.</p></div></div><div className="ownership-card"><div className="ownership-number">C</div><div><h3>Operator review</h3><p>The operator reviews the seller record before activation. Wallet settlement can be added later without changing this contract.</p></div></div></div><div className="developer-boundary"><ShieldCheck size={17} /><div><strong>Security boundary</strong><span>Never expose server credentials in browser code. Treat signed webhook events as the fulfillment signal.</span></div></div></section>
      <section className="developer-section developer-checkout-section" id="checkout"><div className="developer-section-heading"><div><span className="eyebrow">04 · Hosted checkout</span><h2>Let buyers pay from a surface they can trust.</h2><p>The hosted session preserves order context, shows the seller and exact amount, and returns to the marketplace after payment.</p></div><span className="developer-section-index">HOSTED FLOW</span></div><div className="checkout-contract"><div className="checkout-screen"><div className="checkout-screen-top"><span className="public-brand"><img src={logo} alt="" /><strong>druto</strong></span><span className="developer-version">Arc Testnet</span></div><div className="checkout-screen-body"><span className="eyebrow">Payment request</span><h3>8.50 <small>USDC</small></h3><p>Digital access · Secure seller checkout</p><div className="checkout-method-preview"><WalletCards size={17} /><span><strong>Connect wallet</strong><small>Injected EVM wallet or QR</small></span><Check size={15} /></div><button className="button button-primary full-width">Review payment <ArrowRight size={14} /></button></div></div><div className="checkout-rules"><div><WalletCards size={18} /><span><strong>Wallet approval</strong><small>Buyer signs the token transfer in their own wallet.</small></span></div><div><Network size={18} /><span><strong>Arc verification</strong><small>Druto verifies the exact recipient, token, amount, and chain.</small></span></div><div><ExternalLink size={18} /><span><strong>Return URL</strong><small>Use the persisted marketplace URL after the final state.</small></span></div></div></div></section>
      <section className="developer-section" id="verification"><div className="developer-section-heading"><div><span className="eyebrow">05 · Verification boundary</span><h2>Final means verified, not merely submitted.</h2><p>Druto’s state machine distinguishes a created intent, a submitted transaction, verification in progress, and a succeeded payment.</p></div><span className="developer-section-index">ARC FINALITY</span></div><div className="verification-grid"><div className="verification-state"><span className="state-dot state-created" /><strong>requires_payment</strong><small>Intent exists; no transfer observed.</small></div><div className="verification-state"><span className="state-dot state-submitted" /><strong>submitted</strong><small>Transaction hash received; still untrusted.</small></div><div className="verification-state"><span className="state-dot state-verifying" /><strong>verifying</strong><small>Recipient, token, amount, chain, and finality checked.</small></div><div className="verification-state"><span className="state-dot state-succeeded" /><strong>succeeded</strong><small>Safe to fulfill and emit payment.verified.</small></div></div></section>
      <section className="developer-section developer-code-section" id="webhooks"><div className="developer-section-heading"><div><span className="eyebrow">06 · Webhooks and fulfillment</span><h2>Synchronize from signed events.</h2><p>Register one HTTPS endpoint per seller or marketplace, store the secret securely, and make your receiver idempotent.</p></div><span className="developer-section-index">HMAC / RETRY</span></div><div className="developer-code-grid"><div><CodeBlock code={webhookSnippet} /></div><div className="webhook-checklist"><div><ShieldCheck size={18} /><span><strong>Verify the signature</strong><small>Use the raw request body, timestamp tolerance, and endpoint secret.</small></span></div><div><KeyRound size={18} /><span><strong>Reject replays</strong><small>Persist processed event IDs; do not rely on in-memory state.</small></span></div><div><Webhook size={18} /><span><strong>Handle retries</strong><small>Return 2xx only after durable processing or safe enqueue.</small></span></div><div><Check size={18} /><span><strong>Fulfill once</strong><small>Use externalOrderId plus event ID to prevent duplicate delivery.</small></span></div></div></div><div className="event-payload"><span className="eyebrow">payment.verified payload includes</span><div><code>id</code><code>type</code><code>createdAt</code><code>paymentIntentId</code><code>externalOrderId</code><code>marketplaceId</code><code>sellerId</code><code>amount</code><code>asset</code><code>network</code><code>transactionHash</code><code>buyer</code></div></div></section>
      <section className="developer-section developer-reference-section" id="errors"><div className="developer-section-heading"><div><span className="eyebrow">Error reference</span><h2>Failures are typed, actionable, and safe to retry.</h2><p>Map Druto errors to buyer messaging, seller remediation, or an idempotent retry. Never fulfill from an unverified client-side success state.</p></div><span className="developer-section-index">ERRORS</span></div><div className="reference-grid error-reference-grid"><div><h3><code>invalid_return_url</code></h3><p>Use a relative path or an <code>http(s)</code> URL. Reject script schemes and protocol-relative URLs before creating the intent.</p><small>Remediation · validate at your marketplace backend.</small></div><div><h3><code>idempotency_conflict</code></h3><p>The same idempotency key was reused with different order, item, or amount details. Generate a stable key per seller order and do not mutate it.</p><small>Remediation · create a new key only for a new order.</small></div><div><h3><code>seller_not_approved</code></h3><p>The seller is pending or its approved wallet does not match the server-resolved account. Do not send funds until ownership verification and admin approval are complete.</p><small>Remediation · restart seller onboarding.</small></div><div><h3><code>ownership_challenge_invalid</code></h3><p>The wallet signature, domain, nonce, expiry, or single-use state is invalid. The challenge must be signed exactly as returned by Druto.</p><small>Remediation · request a fresh challenge.</small></div><div><h3><code>webhook_signature_invalid</code> / <code>replay</code></h3><p>Reject a bad HMAC, stale timestamp, or already-processed event ID. Verify the raw body and persist event IDs durably before fulfillment.</p><small>Remediation · return a non-2xx response for safe retry.</small></div></div></section>
      <section className="developer-section developer-kit-section" id="sdk-kit"><div className="developer-section-heading"><div><span className="eyebrow">Integration kits</span><h2>Choose the boundary that fits your stack.</h2><p>The standalone SDK is the fastest path; the contract docs keep custom integrations honest.</p></div><span className="developer-section-index">DOWNLOADS</span></div><div className="kit-grid"><article><span className="kit-icon"><FileCode2 size={19} /></span><h3>JavaScript / TypeScript SDK</h3><p>Typed checkout client, request builders, ownership signing, webhook verification, replay helpers, and examples.</p><div className="kit-actions"><a href={sdkPackageUrl} className="button button-primary">Download SDK kit <Download size={14} /></a><a href={sdkGuideUrl} className="button button-quiet">Read GUIDE.md <ExternalLink size={13} /></a><a href={sdkReadmeUrl} className="button button-quiet">Read README.md <ExternalLink size={13} /></a></div><small>Starter package · Arc Testnet</small></article><article><span className="kit-icon"><Terminal size={19} /></span><h3>REST contract</h3><p>Server-side Payment Intent shapes, response fields, errors, idempotency, and seller routing rules for any backend.</p><a href="#reference" className="button button-quiet">Read API reference <ArrowRight size={14} /></a><small>Framework agnostic</small></article><article><span className="kit-icon"><WalletCards size={19} /></span><h3>Wallet onboarding kit</h3><p>Seller challenge flow, exact message construction, signature recovery, admin approval, and secure wallet boundaries.</p><a href="#seller-ownership" className="button button-quiet">View ownership flow <ArrowRight size={14} /></a><small>No transaction required</small></article></div><div className="kit-download-note"><Download size={16} /><span><strong>Starter kit contents</strong><small><code>src/</code> helpers · <code>examples/</code> receiver · <code>README.md</code> · <code>GUIDE.md</code> · tests</small></span><a href="#sdk-kit">Package details <ArrowRight size={13} /></a></div></section>
      <section className="developer-section developer-reference-section" id="reference"><div className="developer-section-heading"><div><span className="eyebrow">Reference</span><h2>Production boundaries, stated plainly.</h2></div><span className="developer-section-index">CHECKLIST</span></div><div className="reference-grid"><div><h3>Before you integrate</h3><ul><li><Check size={14} />Use Arc Testnet chain ID <code>5042002</code>.</li><li><Check size={14} />Use USDC atomic units with 6 decimals.</li><li><Check size={14} />Keep Druto credentials on your server.</li><li><Check size={14} />Use a stable idempotency key per seller order.</li><li><Check size={14} />Persist structured order context for receipts.</li></ul></div><div><h3>Test the unhappy paths</h3><ul><li><Check size={14} />Wrong seller or unapproved destination.</li><li><Check size={14} />Underpaid, overpaid, expired, and duplicate intents.</li><li><Check size={14} />Invalid return URLs and replayed webhooks.</li><li><Check size={14} />A mixed cart with one failing seller intent.</li><li><Check size={14} />A webhook retry after a timeout.</li></ul></div><div><h3>Current testnet boundary</h3><ul><li><Check size={14} />USDC only on Arc Testnet.</li><li><Check size={14} />Direct seller settlement.</li><li><Check size={14} />Hosted buyer payment methods.</li><li><X size={14} />No fiat, card, mainnet, or escrow.</li><li><X size={14} />No private-key custody or signing.</li></ul></div></div></section>
    </main>
    <footer className="developer-footer"><Link href="/" className="public-brand"><img src={logo} alt="" /><strong>druto</strong></Link><span>Build stablecoin commerce on Arc.</span><div><Link href="/dashboard">Dashboard <ArrowRight size={12} /></Link><a href="https://docs.arc.network" target="_blank" rel="noreferrer">Arc docs <ExternalLink size={12} /></a></div></footer>
  </div>;
}
