// Ledger Light reminder: editorial Swiss structure, warm white surfaces, graphite text, cobalt actions, Druto Sea Glass finality, IBM Plex Mono for identifiers, and restrained motion.
import { useMemo, useState } from "react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";
import {
  Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, BadgeCheck, Bell, BookOpen, Box, Check, ChevronDown, CircleDollarSign, Clipboard, Code2, Copy, CreditCard, Database, ExternalLink, FileCheck2, FileText, Gauge, GitBranch, HelpCircle, Home as HomeIcon, KeyRound, LayoutGrid, LifeBuoy, Link2, ListFilter, LockKeyhole, Menu, MoreHorizontal, Network, PauseCircle, Plus, ReceiptText, RefreshCw, Search, Send, Settings2, ShieldCheck, Sparkles, Table2, Terminal, Timer, TrendingUp, UserRound, UsersRound, WalletCards, X, Zap
} from "lucide-react";

const logo = "/manus-storage/druto-arc-mark_c8c084dd.png";
const heroVisual = "/manus-storage/druto-editorial-network_c7fbc025.jpg";
const flowVisual = "/manus-storage/druto-payment-flow_17da128c.jpg";
const settleVisual = "/manus-storage/druto-settlement-abstract_ac9457d1.jpg";

const navGroups = [
  { label: "Operate", items: ["Overview", "Payments", "Payment Links", "Invoices", "Subscriptions"] },
  { label: "Understand", items: ["Customers", "Balances", "Settlements", "Reports"] },
  { label: "Control", items: ["Risk & compliance", "Developers", "Settings"] },
];

const paymentRows = [
  { id: "pay_01J8N2F4", customer: "Northstar AI", amount: "$1,240.00", status: "Succeeded", time: "2 min ago", hash: "0x7a2b…d91c", tone: "success" },
  { id: "pay_01J8N2E8", customer: "Mosaic Labs", amount: "$680.00", status: "Verifying", time: "8 min ago", hash: "0xe884…219a", tone: "warning" },
  { id: "pay_01J8N1V7", customer: "Atlas Compute", amount: "$4,800.00", status: "Succeeded", time: "22 min ago", hash: "0x1c99…7f0a", tone: "success" },
  { id: "pay_01J8MZQ3", customer: "Dawn Studio", amount: "$95.00", status: "Underpaid", time: "48 min ago", hash: "0x91fd…03ad", tone: "danger" },
  { id: "pay_01J8MYA2", customer: "Tangent Works", amount: "$2,100.00", status: "Succeeded", time: "1 hr ago", hash: "0x3dd7…8a51", tone: "success" },
];

const customers = [
  ["Northstar AI", "finance@northstar.ai", "$18,420.00", "Active"],
  ["Mosaic Labs", "ops@mosaic.dev", "$9,680.00", "Active"],
  ["Atlas Compute", "billing@atlas.cloud", "$7,240.00", "Active"],
  ["Dawn Studio", "hello@dawn.studio", "$2,145.00", "Review"],
];

function classNames(...values: Array<string | false | undefined>) { return values.filter(Boolean).join(" "); }

function StatusPill({ status, tone = "neutral" }: { status: string; tone?: string }) {
  const icon = tone === "success" ? <Check size={12} /> : tone === "warning" ? <Timer size={12} /> : tone === "danger" ? <AlertTriangle size={12} /> : <Activity size={12} />;
  return <span className={classNames("status-pill", `status-${tone}`)}>{icon}{status}</span>;
}

function Mark() { return <img src={logo} alt="" className="brand-mark" />; }

function Sidebar({ active, setActive, collapsed, setCollapsed }: { active: string; setActive: (value: string) => void; collapsed: boolean; setCollapsed: (value: boolean) => void }) {
  return <aside className={classNames("sidebar", collapsed && "sidebar-collapsed")}>
    <div className="brand-row"><div className="brand-lockup"><Mark /><span>druto</span></div><button className="icon-button sidebar-toggle" onClick={() => setCollapsed(!collapsed)} aria-label="Toggle navigation"><Menu size={17} /></button></div>
    <div className="environment-switch"><span className="live-dot" /> <span>Test environment</span><ChevronDown size={13} /></div>
    <nav className="side-nav">{navGroups.map(group => <div key={group.label} className="nav-group"><div className="nav-label">{group.label}</div>{group.items.map(item => <button key={item} onClick={() => setActive(item)} className={classNames("nav-item", active === item && "nav-active")}><NavIcon item={item} /><span>{item}</span>{item === "Risk & compliance" && <span className="nav-count">3</span>}</button>)}</div>)}</nav>
    <div className="sidebar-bottom"><button className="nav-item"><LifeBuoy size={17} /><span>Support</span></button><div className="user-card"><div className="avatar">AR</div><div className="user-meta"><strong>Alex Rivera</strong><span>Owner</span></div><MoreHorizontal size={16} /></div></div>
  </aside>;
}

function NavIcon({ item }: { item: string }) {
  const icons: Record<string, any> = { Overview: HomeIcon, Payments: CreditCard, "Payment Links": Link2, Invoices: ReceiptText, Subscriptions: RefreshCw, Customers: UsersRound, Balances: WalletCards, Settlements: Send, Reports: Table2, "Risk & compliance": ShieldCheck, Developers: Code2, Settings: Settings2 };
  const Icon = icons[item] || Box; return <Icon size={17} />;
}

function Topbar({ title, onCreate }: { title: string; onCreate: () => void }) {
  return <header className="topbar"><div className="topbar-title"><div className="breadcrumb">Workspace <span>/</span> Operations</div><h1>{title}</h1></div><div className="topbar-actions"><div className="search-field"><Search size={15} /><input placeholder="Search anything" aria-label="Search" /><kbd>⌘ K</kbd></div><button className="icon-button"><Bell size={17} /><i className="notification-dot" /></button><button className="button button-primary" onClick={onCreate}><Plus size={16} /> Create payment</button></div></header>;
}

function Overview({ setActive, onCreate }: { setActive: (v: string) => void; onCreate: () => void }) {
  const [period, setPeriod] = useState("Last 30 days");
  return <div className="page-content overview-page">
    <section className="hero-panel"><div className="hero-copy"><span className="eyebrow"><span className="eyebrow-line" /> Ledger snapshot · 21 Aug 2026</span><h2>$18,420.64<br /><em>available to settle.</em></h2><p>Your ledger is balanced across 32 finalized payments. $3,920.00 remains pending while three operational items need attention.</p><div className="hero-actions"><button className="button button-primary" onClick={() => setActive("Settlements")}><Send size={16} /> Review settlement</button><button className="button button-quiet" onClick={onCreate}><Plus size={16} /> New payment intent</button></div><div className="hero-footnote"><span><span className="live-dot" /> Arc Testnet</span><span className="foot-divider" /><span>Last reconciled 2 min ago</span></div></div><div className="hero-art"><img src={heroVisual} alt="Abstract ledger network illustration" /><div className="hero-art-note"><span className="arc-ring" /><span><strong>32 FINAL</strong><small>ledger postings</small></span></div><div className="hero-art-label"><span className="arc-line" /> finality signal <strong>0.8s</strong></div></div></section>
    <section className="metric-grid"><Metric label="Gross payments" value="$42,890.00" delta="18.4%" positive icon={<ArrowUpRight size={14} />} /><Metric label="Successful payments" value="98.2%" delta="2.1%" positive icon={<TrendingUp size={14} />} /><Metric label="Available balance" value="$18,420.64" delta="USDC" icon={<WalletCards size={14} />} /><Metric label="To settle" value="$7,240.00" delta="Tomorrow" icon={<Send size={14} />} /></section>
    <section className="overview-grid"><div className="card revenue-card"><div className="card-heading"><div><span className="eyebrow">Volume</span><h3>Payment activity</h3></div><button className="select-button" onClick={() => setPeriod(period === "Last 30 days" ? "Last 7 days" : "Last 30 days")}>{period}<ChevronDown size={14} /></button></div><div className="chart-wrap"><div className="chart-y"><span>$6k</span><span>$4k</span><span>$2k</span><span>$0</span></div><div className="chart"><div className="chart-grid"><i /><i /><i /><i /></div><svg viewBox="0 0 700 210" preserveAspectRatio="none" aria-label="Payment activity chart"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#1e9b83" stopOpacity=".26" /><stop offset="1" stopColor="#1e9b83" stopOpacity="0" /></linearGradient></defs><path d="M0,175 C42,166 58,128 96,145 S151,102 190,123 S240,96 275,109 S321,49 358,82 S407,72 438,98 S489,58 520,68 S570,24 604,56 S661,28 700,38 L700,210 L0,210 Z" fill="url(#chartFill)" /><path d="M0,175 C42,166 58,128 96,145 S151,102 190,123 S240,96 275,109 S321,49 358,82 S407,72 438,98 S489,58 520,68 S570,24 604,56 S661,28 700,38" fill="none" stroke="#1e9b83" strokeWidth="3" /></svg><div className="chart-x"><span>01 Aug</span><span>08 Aug</span><span>15 Aug</span><span>22 Aug</span><span>Today</span></div></div></div><div className="chart-summary"><span><i className="legend-dot sea" /> Payments <strong>$42,890</strong></span><span><i className="legend-dot blue" /> Fees <strong>$429</strong></span><span className="chart-summary-note">Compared with previous period <ArrowUpRight size={14} /></span></div></div><div className="card flow-card"><div className="card-heading"><div><span className="eyebrow">Settlement rail</span><h3>Payment flow</h3></div><button className="icon-button"><MoreHorizontal size={17} /></button></div><img src={flowVisual} alt="Payment flow illustration" /><div className="flow-steps"><FlowStep n="01" label="Request" value="12 active" done /><FlowStep n="02" label="Verify" value="3 reviewing" done /><FlowStep n="03" label="Settle" value="Tomorrow" /></div></div></section>
    <section className="lower-grid"><div className="card table-card"><div className="card-heading"><div><span className="eyebrow">Latest activity</span><h3>Recent payments</h3></div><button className="text-button" onClick={() => setActive("Payments")}>View all <ArrowUpRight size={14} /></button></div><PaymentTable compact /></div><div className="card queue-card"><div className="card-heading"><div><span className="eyebrow">Needs attention</span><h3>Operations queue</h3></div><span className="queue-count">3</span></div><QueueItem icon={<AlertTriangle />} title="Underpaid payment" detail="Dawn Studio · $5 short" action="Review" tone="danger" /><QueueItem icon={<ShieldCheck />} title="Risk review" detail="Wallet screening pending" action="Open case" tone="warning" /><QueueItem icon={<RefreshCw />} title="Webhook retrying" detail="northstar.ai · attempt 2" action="Inspect" tone="neutral" /></div></section>
  </div>;
}

function Metric({ label, value, delta, positive, icon }: { label: string; value: string; delta: string; positive?: boolean; icon: React.ReactNode }) { return <div className="metric-card"><div className="metric-top"><span>{label}</span><span className="metric-icon">{icon}</span></div><strong>{value}</strong><div className={classNames("metric-delta", positive && "positive")}>{positive && <ArrowUpRight size={13} />}{delta}</div></div>; }
function FlowStep({ n, label, value, done }: { n: string; label: string; value: string; done?: boolean }) { return <div className="flow-step"><span className={classNames("flow-number", done && "flow-done")}>{done ? <Check size={12} /> : n}</span><span><strong>{label}</strong><small>{value}</small></span></div>; }
function QueueItem({ icon, title, detail, action, tone }: { icon: React.ReactNode; title: string; detail: string; action: string; tone: string }) { return <div className="queue-item"><span className={classNames("queue-icon", `queue-${tone}`)}>{icon}</span><span className="queue-copy"><strong>{title}</strong><small>{detail}</small></span><button className="small-link" onClick={() => toast.info(`${action} is available in the full operations console.`)}>{action}</button></div>; }

function PaymentTable({ compact = false }: { compact?: boolean }) { return <div className="table-wrap"><table><thead><tr><th>Payment</th><th>Customer</th><th>Amount</th><th>Status</th><th>Received</th></tr></thead><tbody>{paymentRows.slice(0, compact ? 4 : paymentRows.length).map(row => <tr key={row.id}><td><span className="mono-id">{row.id}</span><small className="table-sub"><span className="mini-arc" />{row.hash}</small></td><td>{row.customer}</td><td className="amount-cell">{row.amount}<small>USDC</small></td><td><StatusPill status={row.status} tone={row.tone} /></td><td className="muted-cell">{row.time}</td></tr>)}</tbody></table></div>; }

function PagePanel({ active, onCreate }: { active: string; onCreate: () => void }) {
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<string | null>(null);
  const headings: Record<string, string> = { Payments: "Payments", "Payment Links": "Payment Links", Invoices: "Invoices", Subscriptions: "Subscriptions", Customers: "Customers", Balances: "Balances", Settlements: "Settlements", Reports: "Reports", "Risk & compliance": "Risk & compliance", Developers: "Developers", Settings: "Settings" };
  const title = headings[active] || active;
  if (active === "Payments") return <div className="page-content"><PageHeader eyebrow="Ledger activity" title="Payments" description="Every payment intent, observed transaction, and final ledger posting in one place." action="Create payment" onAction={onCreate} /><div className="filter-bar"><div className="search-field wide"><Search size={15} /><input placeholder="Search by payment, customer, or hash" value={query} onChange={e => setQuery(e.target.value)} /></div><button className="filter-button"><ListFilter size={15} /> Filters</button><button className="filter-button">All statuses <ChevronDown size={14} /></button></div><div className="card table-card full-table"><PaymentTable /></div>{selected && <DetailDrawer id={selected} close={() => setSelected(null)} />}</div>;
  if (active === "Balances") return <BalancesPage />;
  if (active === "Risk & compliance") return <RiskPage />;
  if (active === "Developers") return <DeveloperPage />;
  if (active === "Customers") return <CustomersPage />;
  return <div className="page-content"><PageHeader eyebrow="Operations" title={title} description={`Manage ${title.toLowerCase()} with the same clear, auditable controls as the payment ledger.`} action={active === "Settlements" ? "Request settlement" : "Create new"} onAction={onCreate} /><div className="empty-feature card"><div className="empty-icon"><Sparkles size={21} /></div><h3>{title} workspace</h3><p>This surface is wired for the Druto MVP experience. Connect the deferred API and ledger services later to replace the local test records with live data.</p><div className="empty-actions"><button className="button button-primary" onClick={onCreate}><Plus size={16} /> {active === "Settlements" ? "Request settlement" : "Create record"}</button><button className="button button-quiet" onClick={() => toast.info("This is a frontend-only test environment.")}><BookOpen size={16} /> Read implementation notes</button></div></div><div className="mini-card-row"><div className="card mini-card"><span className="eyebrow">Test environment</span><strong>Local state enabled</strong><small>Nothing here moves real funds.</small></div><div className="card mini-card"><span className="eyebrow">Integration boundary</span><strong>API deferred</strong><small>Ready for future adapter wiring.</small></div><div className="card mini-card"><span className="eyebrow">Audit posture</span><strong>Visible states</strong><small>Every mock action is labeled.</small></div></div></div>;
}

function PageHeader({ eyebrow, title, description, action, onAction }: { eyebrow: string; title: string; description: string; action: string; onAction: () => void }) { return <div className="page-header"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div><button className="button button-primary" onClick={onAction}><Plus size={16} /> {action}</button></div>; }
function BalancesPage() { return <div className="page-content"><PageHeader eyebrow="Ledger-derived" title="Balances" description="Available, pending, and reserved funds are projections of immutable ledger entries." action="View ledger" onAction={() => toast.info("Ledger explorer is part of the deferred API phase.")} /><div className="balance-hero card"><div><span className="eyebrow">Available USDC</span><strong>$18,420.64</strong><p><span className="live-dot" /> Test environment · Arc Testnet</p></div><img src={settleVisual} alt="Settlement abstraction" /></div><div className="balance-grid"><Metric label="Available" value="$18,420.64" delta="Ready to settle" positive icon={<Check size={14} />} /><Metric label="Pending" value="$3,920.00" delta="4 payments" icon={<Timer size={14} />} /><Metric label="Reserved" value="$1,240.00" delta="1 refund" icon={<LockKeyhole size={14} />} /></div><div className="card table-card"><div className="card-heading"><div><span className="eyebrow">Balance movements</span><h3>Recent ledger entries</h3></div><button className="text-button">Export CSV <ArrowDownRight size={14} /></button></div><PaymentTable compact /></div></div>; }
function RiskPage() { return <div className="page-content"><PageHeader eyebrow="Human in the loop" title="Risk & compliance" description="Review cases, wallet signals, and operational holds before they become money movement." action="Open policy settings" onAction={() => toast.info("Policy settings are mocked in this frontend MVP.")} /><div className="risk-banner"><ShieldCheck size={21} /><div><strong>Controls are active in Test environment</strong><span>Wallet screening and sanctions provider connections are deferred. No automated decision here creates a real payout.</span></div><StatusPill status="Monitoring" tone="success" /></div><div className="risk-layout"><div className="card table-card"><div className="card-heading"><div><span className="eyebrow">Review queue</span><h3>Open cases</h3></div><span className="queue-count">3</span></div>{[["CMP-0192", "Wallet screening", "Dawn Studio", "High", "warning"], ["CMP-0188", "Velocity threshold", "Mosaic Labs", "Medium", "neutral"], ["CMP-0181", "Sanctions screening", "Unknown wallet", "Low", "success"]].map(c => <div className="case-row" key={c[0]}><span className="case-id mono-id">{c[0]}</span><span><strong>{c[1]}</strong><small>{c[2]}</small></span><StatusPill status={c[3]} tone={c[4]} /><button className="small-link" onClick={() => toast.info(`Opening ${c[0]} in test mode.`)}>Review</button></div>)}</div><div className="card controls-card"><span className="eyebrow">Policy snapshot</span><h3>Guardrails before settlement</h3><Policy label="Merchant status" value="Approved" ok /><Policy label="Destination allowlist" value="Configured" ok /><Policy label="Velocity rules" value="Active" ok /><Policy label="Human review" value="Required above $5k" /></div></div></div>; }
function Policy({ label, value, ok }: { label: string; value: string; ok?: boolean }) { return <div className="policy-row"><span>{ok ? <Check size={14} /> : <AlertTriangle size={14} />}{label}</span><strong>{value}</strong></div>; }
function DeveloperPage() { const [copied, setCopied] = useState(false); return <div className="page-content"><PageHeader eyebrow="Build with Druto" title="Developers" description="API keys, webhooks, and integration notes for the payment rail you will connect later." action="Create API key" onAction={() => toast.info("API key creation is intentionally deferred until the backend is connected.")} /><div className="developer-grid"><div className="card code-card"><div className="card-heading"><div><span className="eyebrow">Quickstart</span><h3>Create a payment intent</h3></div><Terminal size={18} /></div><div className="code-block"><div className="code-top"><span><i /> test request</span><button onClick={() => { setCopied(true); toast.success("Code copied"); }}><Copy size={13} /> {copied ? "Copied" : "Copy"}</button></div><pre><code>{`curl https://api.druto.example/v1/payment_intents \\\n  -H "Authorization: Bearer druto_test_..." \\\n  -H "Idempotency-Key: order_123" \\\n  -d amount=100000000 \\\n  -d asset=USDC \\\n  -d network=arc`}</code></pre></div><div className="code-note"><InfoDot /> API, auth, and idempotency are represented here as documentation only. No request is sent.</div></div><div className="card endpoint-card"><span className="eyebrow">Integration status</span><h3>Connection map</h3><Endpoint icon={<GitBranch />} label="REST API" status="Deferred" /><Endpoint icon={<Network />} label="Arc Testnet" status="Deferred" /><Endpoint icon={<WalletCards />} label="Circle Wallets" status="Deferred" /><Endpoint icon={<ShieldCheck />} label="Webhook signing" status="Designed" /></div></div><div className="developer-links"><div><Code2 size={18} /><strong>API reference</strong><span>Resources, errors, and idempotency model</span></div><div><FileCheck2 size={18} /><strong>Integration checklist</strong><span>What must be verified before production</span></div><div><LockKeyhole size={18} /><strong>Security guide</strong><span>Keys, scopes, and replay protection</span></div></div></div>; }
function InfoDot() { return <span className="info-dot">i</span>; }
function Endpoint({ icon, label, status }: { icon: React.ReactNode; label: string; status: string }) { return <div className="endpoint-row"><span className="endpoint-icon">{icon}</span><span><strong>{label}</strong><small>Adapter boundary</small></span><StatusPill status={status} tone={status === "Designed" ? "success" : "neutral"} /></div>; }
function CustomersPage() { return <div className="page-content"><PageHeader eyebrow="Relationships" title="Customers" description="Customer records are separate from wallet identity and preserve payment context over time." action="Add customer" onAction={() => toast.success("Customer form opened in test mode.")} /><div className="filter-bar"><div className="search-field wide"><Search size={15} /><input placeholder="Search customers" /></div><button className="filter-button"><ListFilter size={15} /> Filters</button></div><div className="card table-card full-table"><table><thead><tr><th>Customer</th><th>Email</th><th>Payment volume</th><th>Status</th><th /></tr></thead><tbody>{customers.map(c => <tr key={c[0]}><td><div className="customer-cell"><div className="avatar small">{c[0].slice(0, 2).toUpperCase()}</div><strong>{c[0]}</strong></div></td><td className="muted-cell">{c[1]}</td><td className="amount-cell">{c[2]}<small>USDC</small></td><td><StatusPill status={c[3]} tone={c[3] === "Review" ? "warning" : "success"} /></td><td><button className="icon-button"><MoreHorizontal size={16} /></button></td></tr>)}</tbody></table></div></div>; }
function DetailDrawer({ id, close }: { id: string; close: () => void }) { return <div className="drawer-backdrop" onClick={close}><aside className="detail-drawer" onClick={e => e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">Payment detail</span><h3>{id}</h3></div><button className="icon-button" onClick={close}><X size={18} /></button></div><div className="drawer-status"><StatusPill status="Succeeded" tone="success" /><strong>$1,240.00 <small>USDC</small></strong></div><DetailLine label="Payment Intent" value="pi_01J8N2F4" mono /><DetailLine label="Customer" value="Northstar AI" /><DetailLine label="Network" value="Arc Testnet" /><DetailLine label="Finality" value="Final · 0.8s" /><DetailLine label="Transaction" value="0x7a2b…d91c" mono copy /><div className="drawer-section"><span className="eyebrow">Ledger postings</span><div className="posting"><span>Merchant clearing</span><strong>+ $1,227.60</strong></div><div className="posting"><span>Platform fee</span><strong>− $12.40</strong></div></div><button className="button button-quiet full-width" onClick={() => toast.info("Explorer links are disabled in the frontend-only MVP.")}><ExternalLink size={15} /> View on explorer</button></aside></div>; }
function DetailLine({ label, value, mono, copy }: { label: string; value: string; mono?: boolean; copy?: boolean }) { return <div className="detail-line"><span>{label}</span><strong className={mono ? "mono-id" : ""}>{value}{copy && <Copy size={13} />}</strong></div>; }

function CheckoutPage() { const [state, setState] = useState("ready"); const stateText: Record<string, string> = { ready: "Ready to pay", submitted: "Transaction submitted", final: "Payment final" }; return <div className="checkout-shell"><div className="checkout-brand"><Mark /><span>druto</span><span className="checkout-test"><span className="live-dot" /> Test checkout</span></div><main className="checkout-main"><div className="checkout-intro"><span className="eyebrow"><span className="eyebrow-line" /> Hosted Checkout</span><h1>Pay <em>Northstar AI.</em></h1><p>One secure transfer. Final on Arc, recorded in Druto.</p><div className="checkout-trust"><span><ShieldCheck size={15} /> Verified merchant</span><span><Zap size={15} /> Fast finality</span></div></div><div className="checkout-card"><div className="checkout-card-head"><span>Order #NS-1842</span><span className="checkout-expiry"><Timer size={14} /> Expires in 23:48</span></div><div className="checkout-amount"><span>Total due</span><strong>$1,240.00 <small>USDC</small></strong></div><div className="checkout-network"><span className="network-symbol">A</span><span><strong>USDC on Arc</strong><small>Arc Testnet · ERC-20</small></span><BadgeCheck size={17} /></div>{state === "ready" && <><div className="wallet-placeholder"><div className="wallet-ring"><WalletCards size={26} /></div><strong>Connect a wallet to continue</strong><span>Your wallet will only be asked to approve this exact amount.</span><button className="button button-primary full-width" onClick={() => setState("submitted")}><WalletCards size={16} /> Connect wallet</button></div><div className="checkout-note"><LockKeyhole size={13} /> You will review the recipient and amount before signing.</div></>}{state === "submitted" && <div className="wallet-placeholder state-submitted"><div className="submitted-orbit"><RefreshCw size={25} /></div><strong>Transaction submitted</strong><span>We’re waiting for the Arc transaction to reach finality.</span><div className="progress-line"><i /></div><button className="button button-primary full-width" onClick={() => setState("final")}>Simulate finality</button></div>}{state === "final" && <div className="wallet-placeholder state-final"><div className="success-mark"><Check size={26} /></div><strong>Payment final</strong><span>Your payment is recorded and Northstar AI can fulfill your order.</span><div className="final-ref"><span>Payment reference</span><strong className="mono-id">pay_01J8N2F4 <Copy size={13} /></strong></div><button className="button button-primary full-width" onClick={() => toast.success("Returning to merchant…")}>Return to merchant</button></div>}<div className="checkout-footer"><span>Powered by <strong>druto</strong></span><span><LockKeyhole size={12} /> Secure test environment</span></div></div></main></div>; }

export default function Home() { const [location] = useLocation(); if (location.startsWith("/checkout")) return <CheckoutPage />; const [active, setActive] = useState("Overview"); const [collapsed, setCollapsed] = useState(false); const [showCreate, setShowCreate] = useState(false); const title = active === "Overview" ? "Overview" : active; const create = () => setShowCreate(true); return <div className="app-shell"><Sidebar active={active} setActive={setActive} collapsed={collapsed} setCollapsed={setCollapsed} /><main className="main-shell"><Topbar title={title} onCreate={create} />{active === "Overview" ? <Overview setActive={setActive} onCreate={create} /> : <PagePanel active={active} onCreate={create} />}</main>{showCreate && <CreatePayment close={() => setShowCreate(false)} />}</div>; }

function CreatePayment({ close }: { close: () => void }) { const [created, setCreated] = useState(false); return <div className="modal-backdrop" onClick={close}><div className="modal-card" onClick={e => e.stopPropagation()}>{!created ? <><div className="modal-head"><div><span className="eyebrow">Test environment</span><h3>Create payment intent</h3></div><button className="icon-button" onClick={close}><X size={18} /></button></div><p className="modal-description">Create a backend-generated payment request. This frontend-only version stores the preview locally and does not move funds.</p><label>Amount<input className="form-input" defaultValue="1240.00" /></label><div className="form-two"><label>Asset<select className="form-input"><option>USDC</option></select></label><label>Network<select className="form-input"><option>Arc Testnet</option></select></label></div><label>Description<input className="form-input" defaultValue="Order #NS-1842" /></label><div className="modal-actions"><button className="button button-quiet" onClick={close}>Cancel</button><button className="button button-primary" onClick={() => setCreated(true)}><Plus size={15} /> Create intent</button></div></> : <div className="created-state"><div className="success-mark"><Check size={24} /></div><span className="eyebrow">Payment Intent created</span><h3>Ready for checkout.</h3><p className="mono-id">pi_01J8N4W2</p><button className="button button-primary full-width" onClick={close}>Done</button></div>}</div></div>; }
