import { ArrowRight, Check, Code2, ExternalLink, Layers3, LockKeyhole, Network, Play, ShieldCheck, Sparkles, WalletCards, Webhook } from "lucide-react";
import { Link } from "wouter";

const logo = "/manus-storage/druto-arc-mark_c8c084dd.png";
const heroVisual = "/manus-storage/druto-editorial-network_c7fbc025.jpg";

function Brand() {
  return <Link href="/" className="public-brand"><img src={logo} alt="" /><strong>druto</strong></Link>;
}

export default function Landing() {
  return <div className="public-site">
    <header className="public-nav"><Brand /><nav><a href="#product">Product</a><a href="#how-it-works">How it works</a><Link href="/developers">Developers</Link></nav><div className="public-nav-actions"><Link href="/developers" className="public-nav-link">Docs <ExternalLink size={13} /></Link><Link href="/dashboard" className="button button-primary public-nav-cta">Open dashboard <ArrowRight size={14} /></Link></div></header>
    <main>
      <section className="public-hero" id="product"><div className="public-hero-copy"><span className="public-kicker"><span className="live-dot" /> Arc Testnet</span><h1>Stablecoin payments, built for <em>the real flow.</em></h1><p>Druto gives marketplaces and internet businesses the payment intents, hosted checkout, wallet verification, and signed events they need to move USDC with confidence.</p><div className="public-hero-actions"><Link href="/dashboard" className="button button-primary public-large-button">Open dashboard <ArrowRight size={16} /></Link><Link href="/developers" className="button button-quiet public-large-button">Read developer docs <Code2 size={16} /></Link></div><div className="public-proof-row"><span><Check size={14} /> Non-custodial checkout</span><span><Check size={14} /> Server-resolved sellers</span><span><Check size={14} /> Arc Testnet native</span></div></div><div className="public-hero-visual"><img src={heroVisual} alt="Abstract network visualization" /><div className="public-hero-card"><div className="public-hero-card-top"><span className="public-status"><span className="live-dot" /> Live rail</span><span className="mono-id">ARC / USDC</span></div><strong>Payment verified.</strong><div className="public-hero-card-line"><span>Seller settlement</span><b>+ 125.00 USDC</b></div><div className="public-hero-card-line"><span>Finality</span><b>Arc Testnet</b></div></div><div className="public-hero-coordinate">ARC CONFIRMATION <strong>0x…7f0a</strong></div></div></section>
      <section className="public-trust-strip"><span>One integration boundary</span><strong>From cart to confirmation</strong><span>Wallet · QR · Webhook</span><span>USDC on Arc</span></section>
      <section className="public-section public-product-grid"><div className="public-section-intro"><span className="eyebrow">The payment layer</span><h2>Everything your payment flow needs. Nothing that takes custody.</h2><p>Keep your marketplace logic, your sellers, and your customer relationship. Druto handles the payment state, verification, and operational record.</p></div><div className="public-feature-grid"><article><span className="public-feature-icon"><Layers3 size={18} /></span><h3>Payment Intents</h3><p>Lock amount, asset, seller, order context, and return flow before a buyer signs.</p><Link href="/developers#payment-intents">Explore intents <ArrowRight size={14} /></Link></article><article><span className="public-feature-icon"><WalletCards size={18} /></span><h3>Hosted checkout</h3><p>Give buyers a familiar wallet or QR payment surface with clear Arc Testnet review states.</p><Link href="/developers#checkout">See checkout flow <ArrowRight size={14} /></Link></article><article><span className="public-feature-icon"><Webhook size={18} /></span><h3>Signed events</h3><p>Synchronize fulfillment from replay-safe payment.verified events with delivery tracking.</p><Link href="/developers#webhooks">Read webhook docs <ArrowRight size={14} /></Link></article></div></section>
      <section className="public-section public-flow-section" id="how-it-works"><div className="public-flow-visual"><div className="flow-orbit orbit-a" /><div className="flow-orbit orbit-b" /><div className="flow-core"><img src={logo} alt="" /><strong>druto</strong><small>verified rail</small></div><div className="flow-node node-cart"><span>01</span><strong>Cart</strong><small>Marketplace order</small></div><div className="flow-node node-wallet"><span>02</span><strong>Wallet</strong><small>Buyer signs USDC</small></div><div className="flow-node node-ledger"><span>03</span><strong>Ledger</strong><small>Verified on Arc</small></div></div><div className="public-flow-copy"><span className="eyebrow">A clear path to finality</span><h2>Your marketplace stays in control.</h2><div className="public-step-list"><div><b>01</b><span><strong>Create the intent</strong><small>Your backend sends the seller identity and order context.</small></span></div><div><b>02</b><span><strong>Open hosted checkout</strong><small>Druto gives the buyer wallet and QR options on Arc.</small></span></div><div><b>03</b><span><strong>Verify and fulfill</strong><small>Signed webhooks let you release the order exactly once.</small></span></div></div><Link href="/developers#quickstart" className="text-button public-inline-link">View the integration sequence <ArrowRight size={14} /></Link></div></section>
      <section className="public-section public-callout"><div><span className="public-kicker"><Sparkles size={14} /> Built for marketplace operators</span><h2>Start with Arc Testnet. Design for production.</h2><p>Use the dashboard to see verified payment state. Use the Developer Hub to build the integration your marketplace actually owns.</p></div><div className="public-callout-actions"><Link href="/dashboard" className="button button-primary">Enter dashboard <ArrowRight size={15} /></Link><Link href="/developers" className="button button-quiet">Open Developer Hub <Code2 size={15} /></Link></div></section>
      <section className="public-bottom-grid"><div><span className="eyebrow">Security posture</span><h3>Proof before activation. Verification before fulfillment.</h3><p><ShieldCheck size={15} /> Seller wallets are confirmed with an offchain signature challenge. Payment transactions are verified against Arc Testnet before appearing as final.</p></div><div><span className="eyebrow">Integration surface</span><h3>One contract for any marketplace.</h3><p><Network size={15} /> JavaScript SDK, server contract types, wallet login, hosted checkout, webhooks, and test fixtures are documented in one public hub.</p></div><div><span className="eyebrow">Boundary</span><h3>No keys. No custody. No silent state.</h3><p><LockKeyhole size={15} /> Druto never asks for a private key. Buyers sign from their wallets; operators see an auditable state transition.</p></div></section>
    </main>
    <footer className="public-footer"><Brand /><span>Stablecoin payments on Arc Testnet.</span><div><Link href="/developers">Developer Hub</Link><Link href="/dashboard">Dashboard</Link><a href="https://docs.arc.network" target="_blank" rel="noreferrer">Arc docs <ExternalLink size={12} /></a></div></footer>
  </div>;
}
