import { ArrowRight, Check, Clipboard, Code2, KeyRound, LockKeyhole, ShieldCheck, WalletCards, Webhook } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { copyTextToClipboard, type CopyFeedback } from "@/lib/clipboard";

const logo = "/DRUTO_D_logo.png";
const starterZipUrl = "/manus-storage/druto-nextjs-starter-0.1.0_b97da8c9.zip";
const installSnippet = `pnpm add @druto/sdk\n\n# During local development\npnpm add ../druto-sdk`;
const serverSnippet = `import { DrutoCheckout } from "@druto/sdk";\n\nconst druto = new DrutoCheckout({\n  environment: "testnet",\n  network: "arc",\n  asset: "USDC",\n  checkoutBaseUrl: process.env.DRUTO_CHECKOUT_BASE_URL!,\n  createPayment: async (request) => {\n    const response = await fetch(process.env.DRUTO_CREATE_INTENT_ENDPOINT!, {\n      method: "POST",\n      headers: {\n        "content-type": "application/json",\n        authorization: \`Bearer \${process.env.DRUTO_API_KEY}\`,\n      },\n      body: JSON.stringify({ json: request }),\n    });\n    return (await response.json()).result.data.json;\n  },\n});`;
const webhookSnippet = `const rawBody = await request.text();\nconst signature = request.headers.get("druto-signature") ?? "";\n\nconst valid = await verifyWebhookSignature(\n  process.env.DRUTO_WEBHOOK_SECRET!,\n  rawBody,\n  signature,\n);\n\nif (!valid) return new Response("invalid signature", { status: 401 });\nawait fulfillOrderOnce(event.data.externalOrderId);`;

function CopyBlock({ code, language = "typescript" }: { code: string; language?: string }) {
  const [feedback, setFeedback] = useState<CopyFeedback>("idle");
  const copy = async () => {
    const succeeded = await copyTextToClipboard(code);
    setFeedback(succeeded ? "copied" : "error");
    window.setTimeout(() => setFeedback("idle"), 1800);
  };
  const label = feedback === "copied" ? "Copied" : feedback === "error" ? "Select manually" : "Copy";
  const Icon = feedback === "copied" ? Check : Clipboard;
  return <div className="dev-code-block"><div className="dev-code-head"><span><span className="dev-code-dot" /> {language}</span><button type="button" onClick={copy} aria-label={`Copy ${language} code`}><Icon size={13} /> {label}</button></div><pre><code>{code}</code></pre><span className="sr-only" role="status" aria-live="polite">{feedback === "copied" ? "Code copied to clipboard." : feedback === "error" ? "Copy failed. Select the code manually." : ""}</span></div>;
}

export default function StartWithDruto() {
  return <div className="developer-site start-site">
    <header className="developer-nav"><Link href="/" className="public-brand"><img src={logo} alt="" /><strong>druto</strong></Link><div className="developer-nav-center"><Link href="/developers">Developer Hub</Link><span className="developer-nav-active">Start with Druto</span><a href="#quickstart">Quickstart</a><a href="#webhooks">Webhooks</a></div><div className="developer-nav-actions"><span className="developer-version">Arc Testnet</span><Link href="/dashboard" className="button button-primary">Open dashboard <ArrowRight size={14} /></Link></div></header>
    <main>
      <section className="developer-hero start-hero"><div><span className="public-kicker"><Code2 size={14} /> New seller quickstart</span><h1>Start accepting USDC in a <em>few clear steps.</em></h1><p>Connect your website to Druto without handling private keys. Register a seller, create a server-side Payment Intent, open hosted wallet checkout, and fulfill only after Arc verification.</p><div className="developer-hero-actions"><a href="#quickstart" className="button button-primary public-large-button">Follow the setup <ArrowRight size={16} /></a><Link href="/developers" className="button button-quiet public-large-button">Read the full Developer Hub</Link></div></div><aside className="developer-hero-panel"><div className="dev-panel-top"><span><span className="live-dot" /> Ready for testnet</span><span className="mono-id">v0.1</span></div><div className="dev-panel-line"><span>Asset</span><strong>USDC</strong></div><div className="dev-panel-line"><span>Network</span><strong>Arc Testnet</strong></div><div className="dev-panel-line"><span>Buyer flow</span><strong>Wallet + QR</strong></div><div className="dev-panel-line"><span>Fulfillment</span><strong>Signed event</strong></div><div className="dev-panel-foot"><ShieldCheck size={14} /> No seed phrase or private key</div></aside></section>
      <section className="developer-stat-row"><div><strong>01</strong><span>seller identity</span></div><div><strong>02</strong><span>server credentials</span></div><div><strong>03</strong><span>checkout surfaces</span></div><div><strong>04</strong><span>verified event</span></div></section>
      <section className="developer-section" id="quickstart"><div className="developer-section-heading"><div><span className="eyebrow">The setup</span><h2>From “I have a website” to a verified payment.</h2><p>Keep the commerce system in your application and let Druto own the payment boundary.</p></div><span className="developer-section-index">01 / 06</span></div><div className="developer-steps"><article><span>01</span><div><h3>Create your seller identity</h3><p>Choose a stable marketplace ID and seller ID. The ID stays the same even if the display name changes.</p><a href="#credentials" className="developer-doc-link">See the credential map <ArrowRight size={14} /></a></div></article><article><span>02</span><div><h3>Register the payment destination</h3><p>Submit the payment destination used by the seller record. The account starts pending for operator review.</p><a href="#ownership" className="developer-doc-link">Future payment rail <ArrowRight size={14} /></a></div></article><article><span>03</span><div><h3>Generate server credentials</h3><p>Create an API key and register an HTTPS webhook. Save each one-time secret in your backend environment.</p><a href="#credentials" className="developer-doc-link">Credentials <ArrowRight size={14} /></a></div></article><article><span>04</span><div><h3>Add the backend adapter</h3><p>Install the SDK and create Payment Intents from your server after recalculating the trusted order total.</p><a href="#backend" className="developer-doc-link">Backend starter <ArrowRight size={14} /></a></div></article><article><span>05</span><div><h3>Open hosted payment flow</h3><p>Return a safe checkout URL to the buyer. Druto owns the hosted payment handoff for the exact amount when the payment rail is enabled.</p><a href="#checkout" className="developer-doc-link">Checkout flow <ArrowRight size={14} /></a></div></article><article><span>06</span><div><h3>Fulfill after verification</h3><p>Verify the signed payment.verified event, deduplicate it, and mark the order paid once.</p><a href="#webhooks" className="developer-doc-link">Webhook flow <ArrowRight size={14} /></a></div></article></div></section>
      <section className="developer-section developer-code-section" id="credentials"><div className="developer-section-heading"><div><span className="eyebrow">Your credential map</span><h2>Two secrets. One payment link.</h2><p>The API key authorizes Dashda or any seller website to call Druto. The webhook secret authenticates events sent back to that website.</p></div><span className="developer-section-index">SERVER ONLY</span></div><div className="developer-contract-grid"><div className="card p-6"><KeyRound size={20} /><h3 className="mt-3">API key</h3><p className="mt-2 text-muted-foreground">Use it from your backend to create Payment Intents and retrieve payment state. It is never safe in browser code.</p><div className="credential-example">DRUTO_API_KEY=<strong>druto_test_••••</strong></div></div><div className="card p-6"><Webhook size={20} /><h3 className="mt-3">Webhook secret</h3><p className="mt-2 text-muted-foreground">Use it to verify the raw signed `payment.verified` request before parsing or fulfilling an order.</p><div className="credential-example">DRUTO_WEBHOOK_SECRET=<strong>••••••••</strong></div></div></div><div className="developer-boundary"><LockKeyhole size={17} /><div><strong>Never expose credentials</strong><span>Do not put them in `VITE_` or `NEXT_PUBLIC_` variables, GitHub, a mobile bundle, or a browser request.</span></div></div></section>
      <section className="developer-section developer-code-section" id="backend"><div className="developer-section-heading"><div><span className="eyebrow">Copy-paste backend</span><h2>Start with the smallest useful adapter.</h2><p>Use the included Next.js starter template for a working server boundary, then replace the example order lookup with your store database.</p></div><span className="developer-section-index">NEXT.JS</span></div><div className="developer-code-grid"><CopyBlock code={installSnippet} language="bash" /><CopyBlock code={serverSnippet} /></div><div className="developer-contract-grid"><div><span className="eyebrow">Payment request must include</span><ul>{["externalOrderId — your order reference", "idempotencyKey — stable retry key", "amount — server-calculated USDC amount", "seller.marketplaceId + seller.sellerId", "returnUrl — buyer receipt destination"].map(item => <li key={item}><Check size={14} />{item}</li>)}</ul></div><div><span className="eyebrow">Then save</span><p>Store `paymentIntentId`, seller ID, amount, status, and eventually the Arc `transactionHash` in your own order-payment table.</p><span className="contract-note"><ShieldCheck size={13} /> Your database remains the commerce source of truth.</span></div></div></section>
      <section className="developer-section developer-checkout-section" id="checkout"><div className="developer-section-heading"><div><span className="eyebrow">Buyer experience</span><h2>Hosted checkout integration.</h2><p>Customers return to your site after Druto creates a payment intent. Wallet settlement modules are intentionally disabled in this release and can be added later without changing the order or webhook contract.</p></div><span className="developer-section-index">HOSTED</span></div><div className="checkout-rules"><div><ShieldCheck size={18} /><span><strong>Server-created intents</strong><small>Recalculate the order total on your backend before creating an intent.</small></span></div><div><Webhook size={18} /><span><strong>Signed synchronization</strong><small>Use the webhook event as the source for fulfillment, not a browser redirect.</small></span></div><div><ArrowRight size={18} /><span><strong>Wallet module later</strong><small>The settlement adapter can be restored as an isolated payment rail.</small></span></div></div></section>
      <section className="developer-section" id="ownership"><div className="developer-section-heading"><div><span className="eyebrow">Future payment rail</span><h2>Wallet ownership verification is paused.</h2><p>The current release keeps seller identities, payment destinations, API credentials, and webhook synchronization intact while wallet signing is removed. A future wallet module can reintroduce ownership proof behind the same seller record.</p></div><span className="developer-section-index">PAUSED</span></div><div className="verification-grid"><div className="verification-state"><span className="state-dot state-created" /><strong>seller record</strong><small>Identity and payment destination are stored.</small></div><div className="verification-state"><span className="state-dot state-submitted" /><strong>credentials</strong><small>API key and webhook secret are provisioned.</small></div><div className="verification-state"><span className="state-dot state-verifying" /><strong>webhook</strong><small>Signed payment events remain available.</small></div><div className="verification-state"><span className="state-dot state-succeeded" /><strong>later</strong><small>Wallet proof can be added as a separate module.</small></div></div></section>
      <section className="developer-section developer-code-section" id="webhooks"><div className="developer-section-heading"><div><span className="eyebrow">Keep your orders in sync</span><h2>Fulfill from signed events, not redirects.</h2><p>Register one HTTPS endpoint for your website or marketplace. Verify the raw body, reject stale signatures, deduplicate the event ID, and fulfill once.</p></div><span className="developer-section-index">HMAC / RETRY</span></div><div className="developer-code-grid"><CopyBlock code={webhookSnippet} /><div className="webhook-checklist"><div><ShieldCheck size={18} /><span><strong>Verify HMAC</strong><small>Use `DRUTO_WEBHOOK_SECRET` and the raw request body.</small></span></div><div><KeyRound size={18} /><span><strong>Deduplicate</strong><small>Persist `x-druto-event-id` before fulfillment.</small></span></div><div><Webhook size={18} /><span><strong>Return 2xx after durable work</strong><small>Druto can retry failed deliveries with the same event ID.</small></span></div><div><Check size={18} /><span><strong>Reconcile</strong><small>Match external order ID, intent ID, seller ID, and transaction hash.</small></span></div></div></div></section>
      <section className="developer-callout"><div><span className="eyebrow">Ready for the first test payment?</span><h2>Register your seller, then open your first Druto checkout.</h2><p>Start on Arc Testnet with USDC and a disposable test wallet. Keep your production credentials and funds out of the demo.</p></div><div className="developer-hero-actions"><Link href="/dashboard" className="button button-primary">Open seller setup <ArrowRight size={16} /></Link><a href={starterZipUrl} className="button button-quiet" download><Code2 size={15} /> Download Next.js starter</a></div></section>
    </main>
    <footer className="developer-footer"><span>Druto · Arc Testnet seller quickstart</span><div><Link href="/developers">Developer Hub</Link><Link href="/">Product</Link><Link href="/dashboard">Dashboard</Link></div></footer>
  </div>;
}
